# Generated by Django 3.2.4 on 2021-06-05 08:29

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('password', models.CharField(max_length=254, validators=[api.models.validate_password])),
                ('fullName', models.CharField(max_length=254)),
                ('phone', models.IntegerField(max_length=10)),
                ('address', models.TextField(max_length=254)),
                ('city', models.CharField(max_length=254)),
                ('state', models.CharField(max_length=254)),
                ('country', models.CharField(max_length=254)),
                ('pincode', models.IntegerField(max_length=6)),
            ],
        ),
    ]
