# Generated by Django 3.2.4 on 2021-06-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210605_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cms',
            name='address',
            field=models.TextField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cms',
            name='city',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cms',
            name='country',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cms',
            name='state',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
