# Generated by Django 3.2.4 on 2021-06-05 09:33

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210605_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('username', models.CharField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=254, validators=[django.core.validators.EmailValidator()])),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('password', models.CharField(max_length=254, validators=[api.models.validate_password])),
                ('fullName', models.CharField(max_length=254)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10,10}$')])),
                ('address', models.TextField(blank=True, max_length=254)),
                ('city', models.CharField(blank=True, max_length=254)),
                ('state', models.CharField(blank=True, max_length=254)),
                ('country', models.CharField(blank=True, max_length=254)),
                ('pincode', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{1,6}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Contitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('body', models.TextField(max_length=300)),
                ('summary', models.TextField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='CMS',
        ),
    ]
